version: '3.8'

services:
  mongo-auth:
    image: mongo:6.0
    container_name: mongo-auth
    ports:
      - "27020:27017"
    volumes:
      - mongo-auth-data:/data/db
      - ./mongo-auth-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: auth_user
      MONGO_INITDB_ROOT_PASSWORD: auth_user_password
    networks:
      - internal

  mongo-event:
    image: mongo:6.0
    container_name: mongo-event
    ports:
      - "27021:27017"
    volumes:
      - mongo-event-data:/data/db
      - ./mongo-event-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: event_user
      MONGO_INITDB_ROOT_PASSWORD: event_user_password
    networks:
      - internal

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - internal

  auth-api:
    build:
      context: ./auth-api
      dockerfile: ../docker/Dockerfile-auth
    container_name: auth-api
    # ports 제거 (외부 노출 차단)
    environment:
      SERVER_PORT: 3010
      MONGO_DB_URI: mongodb://auth_user:auth_user_password@mongo-auth:27017/auth?authSource=auth
      JWT_SECRET: DMLALRKDJQTDLWKRTJDGKSMSKEY
      REDIS_URI: redis://redis:6379
      ADMIN_ROLE_CODE: Ad2025min05!@Secret!Key123~!
      OPERATOR_ROLE_CODE: Op2025rator05!@Secret!Key456~!
      AUDITOR_ROLE_CODE: Au2025dit05!@Secret!Key789~!
    networks:
      - internal
      - gateway-link

  event-api:
    build:
      context: ./event-api
      dockerfile: ../docker/Dockerfile-event
    container_name: event-api
    # ports 제거 (외부 노출 차단)
    environment:
      SERVER_PORT: 3011
      MONGO_DB_URI: mongodb://event_user:event_user_password@mongo-event:27017/event?authSource=event
    networks:
      - internal
      - gateway-link

  gateway-api:
    build:
      context: ./gateway-api
      dockerfile: ../docker/Dockerfile-gateway
    container_name: gateway-api
    ports:
      - "3012:3012" # gateway만 외부 노출
    depends_on:
      - auth-api
      - event-api
    environment:
      SERVER_PORT: 3012
      JWT_SECRET: DMLALRKDJQTDLWKRTJDGKSMSKEY
      AUTH_SERVER_API_URL: http://auth-api:3010
      EVENT_SERVER_API_URL: http://event-api:3011
    networks:
      - public
      - gateway-link

volumes:
  mongo-auth-data:
  mongo-event-data:

networks:
  public:
  internal:
    internal: true
  gateway-link:
